version: "3.8"
services: 
    cake_mongodb:
        image: mongo
        container_name: cake_mongodb
        environment: 
            - PUID=1000
            - PGID=1000
        volumes:
            - ./database:/data/db 
        ports: 
            - 27017:27017
